definitions:
  helpers.Response:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
      status:
        type: boolean
    type: object
  models.UserBase:
    properties:
      age:
        type: integer
      gender:
        type: string
      name:
        type: string
    type: object
info:
  contact: {}
  title: MASTER API
  version: "1.0"
paths:
  /api/v1/user/:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helpers.Response'
      tags:
      - User
    post:
      parameters:
      - description: User object to be created
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.UserBase'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/helpers.Response'
      tags:
      - User
swagger: "2.0"
